
//you can customize the request (therefore the log output as well)
//by adding suffixes to the url using "?"" 
GET http://localhost:3000/products/3?playerOne=5

//to isolate an array item in products.js type this:
//GET http://localhost:3000/products/1 

###
POST http://localhost:3000/add
Content-Type: application/json

{
    "title": "test",
    "id": 5
    }